add lingua and see a build break
$ mv ../main.go .
$  cat main.go
package main

import (
	_ "github.com/pemistahl/lingua-go"
	_ "github.com/pemistahl/lingua-go/serialization"
)

func main() {

}
$  bazel run @rules_go//go mod init
INFO: Analyzed target @@rules_go+//go:go (2 packages loaded, 12 targets configured).
INFO: Found 1 target...
Target @@rules_go+//go/tools/go_bin_runner:go_bin_runner up-to-date:
  bazel-bin/external/rules_go+/go/tools/go_bin_runner/bin/go
INFO: Elapsed time: 0.634s, Critical Path: 0.43s
INFO: 7 processes: 4 internal, 3 darwin-sandbox.
INFO: Build completed successfully, 7 total actions
INFO: Running command line: bazel-bin/external/rules_go+/go/tools/go_bin_runner/bin/go <args omitted>
go: creating new go.mod: module github.com/jmhodges/bazel_bugs
go: to add module requirements and sums:
	go mod tidy

$  bazel run @rules_go//go -- get  github.com/pemistahl/lingua-go
INFO: Analyzed target @@rules_go+//go:go (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target @@rules_go+//go/tools/go_bin_runner:go_bin_runner up-to-date:
  bazel-bin/external/rules_go+/go/tools/go_bin_runner/bin/go
INFO: Elapsed time: 0.149s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/external/rules_go+/go/tools/go_bin_runner/bin/go <args omitted>
go: added github.com/pemistahl/lingua-go v1.4.0
go: added github.com/shopspring/decimal v1.3.1
go: added golang.org/x/exp v0.0.0-20221106115401-f9659909a136
go: added google.golang.org/protobuf v1.31.0
rules_go: Marking requested modules as direct dependencies...
$  bazel run @rules_go//go mod tidy
INFO: Analyzed target @@rules_go+//go:go (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target @@rules_go+//go/tools/go_bin_runner:go_bin_runner up-to-date:
  bazel-bin/external/rules_go+/go/tools/go_bin_runner/bin/go
INFO: Elapsed time: 0.148s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/external/rules_go+/go/tools/go_bin_runner/bin/go <args omitted>
$  bazel run //:gazelle
INFO: Analyzed target //:gazelle (0 packages loaded, 81 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 0.182s, Critical Path: 0.01s
INFO: 1 process: 66 action cache hit, 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/gazelle

$  bazel build //:bazel_bugs_lib
ERROR: no such package '@@[unknown repo 'com_github_pemistahl_lingua_go' requested from @@]//': The repository '@@[unknown repo 'com_github_pemistahl_lingua_go' requested from @@]' could not be resolved: No repository visible as '@com_github_pemistahl_lingua_go' from main repository
ERROR: /Users/jmhodges/src/github.com/jmhodges/bazel_bugs/BUILD.bazel:6:11: no such package '@@[unknown repo 'com_github_pemistahl_lingua_go' requested from @@]//': The repository '@@[unknown repo 'com_github_pemistahl_lingua_go' requested from @@]' could not be resolved: No repository visible as '@com_github_pemistahl_lingua_go' from main repository and referenced by '//:bazel_bugs_lib'
ERROR: Analysis of target '//:bazel_bugs_lib' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.161s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully

$ echo 'go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")' >> MODULE.bazel

$  bazel run //:gazelle
INFO: Analyzed target //:gazelle (39 packages loaded, 1019 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 0.885s, Critical Path: 0.00s
INFO: 4 processes: 61 action cache hit, 4 internal.
INFO: Build completed successfully, 4 total actions
INFO: Running command line: bazel-bin/gazelle

$  bazel build //:bazel_bugs_lib
INFO: Analyzed target //:bazel_bugs_lib (0 packages loaded, 2 targets configured).
ERROR: /private/var/tmp/_bazel_jmhodges/eb16c8c3f4af4addfaf08c38f6204969/external/gazelle++go_deps+com_github_pemistahl_lingua_go/BUILD.bazel:3:11: GoCompilePkg external/gazelle++go_deps+com_github_pemistahl_lingua_go/lingua-go.a failed: (Exit 1): builder failed: error executing GoCompilePkg command (from target @@gazelle++go_deps+com_github_pemistahl_lingua_go//:lingua-go) bazel-out/darwin_arm64-opt-exec-ST-d57f47055a04/bin/external/rules_go++go_sdk+go_default_sdk/builder_reset/builder compilepkg -sdk external/rules_go++go_sdk+go_default_sdk -goroot ... (remaining 50 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
compilepkg: missing strict dependencies:
	/private/var/tmp/_bazel_jmhodges/eb16c8c3f4af4addfaf08c38f6204969/sandbox/darwin-sandbox/526/execroot/_main/external/gazelle++go_deps+com_github_pemistahl_lingua_go/detector.go: import of "github.com/pemistahl/lingua-go/serialization"
	/private/var/tmp/_bazel_jmhodges/eb16c8c3f4af4addfaf08c38f6204969/sandbox/darwin-sandbox/526/execroot/_main/external/gazelle++go_deps+com_github_pemistahl_lingua_go/writer.go: import of "github.com/pemistahl/lingua-go/serialization"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
Target //:bazel_bugs_lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.266s, Critical Path: 0.06s
INFO: 2 processes: 327 action cache hit, 2 internal.
ERROR: Build did NOT complete successfully